source 'https://rubygems.org'

gem 'bundler', '~> 1.13'
gem 'rake', '~> 10.0'
gem 'rspec', '~> 3.0'
gem 'pg', '~> 0.20'
gem 'dotenv'
gem 'activerecord', '~> 5.0'
gem 'httparty'
gem 'pry'
gem 'rb-readline'
